name: BuildList

on:
  workflow_dispatch:

env:
  GH_USERNAME: ${{ github.actor }}
  
jobs:

  runCode:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build List

        run: |
          git config --global user.name "${GH_USERNAME}"
          git config --global user.email "${GH_USERNAME}@users.noreply.github.com"
          git config user.email 
          git config user.name
          git rm iptv_liste.m3u
          git commit -am "iptv_liste.m3u deleted"
          chmod +x exec_mergeFiles.sh && ./exec_mergeFiles.sh
          git add -f iptv_liste.m3u
          git status
          git commit -m "iptv_liste.m3u playlist updated."
          git push
