name: MergeList

on:
  workflow_dispatch:

env:
  GH_USERNAME: ${{ github.actor }}
  CHANNEL_LIST: 'iptv_liste'
  
jobs:

  runCode:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Merge Files

        run: |
          git config --global user.name "${GH_USERNAME}"
          git config --global user.email "${GH_USERNAME}@users.noreply.github.com"
          git config user.email 
          git config user.name
          git rm ${CHANNEL_LIST}.m3u
          git commit -am "${CHANNEL_LIST}.m3u deleted"
          chmod +x exec_mergeFiles.sh && ./exec_mergeFiles.sh
          git add -f ${CHANNEL_LIST}.m3u
          git status
          git commit -m "${CHANNEL_LIST}.m3u playlist updated."
          git push
