name: LinkGrabber

on:
  schedule:
    - cron: '0 */3 * * *'

  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
env:
  GH_USERNAME: ${{ github.actor }}
  
jobs:

  runCode:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Grab Link

        run: |
          git config --global user.name "${GH_USERNAME}"
          git config --global user.email "${GH_USERNAME}@users.noreply.github.com"
          git config user.email 
          git config user.name
          git rm euronews.m3u
          git rm iptv_list.m3u
          git commit -a -m "m3u files deleted"
          chmod +x exec_grabber.sh && ./exec_grabber.sh
          git status
          git add -
          git status
          git commit -a -m "m3u Playlists updated."
          git push
