name: OnDemandGrabber

on:
  workflow_dispatch:

env:
  GH_USERNAME: ${{ github.actor }}
  
jobs:

  runCode:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Grab OnDemand

        run: |
          git config --global user.name "${GH_USERNAME}"
          git config --global user.email "${GH_USERNAME}@users.noreply.github.com"
          git config user.email 
          git config user.name
          chmod +x exec_grabbOD.sh && ./exec_grabbOD.sh
          git status
          git add .
          git status
          git commit -a -m "Playlist updated."
          git push
