name: OnDemandGrabber

on:
  workflow_dispatch:

env:
  GH_USERNAME: ${{ github.actor }}
  
jobs:

  runCode:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Grab OnDemand

        run: |
          git config --global user.name "${GH_USERNAME}"
          git config --global user.email "${GH_USERNAME}@users.noreply.github.com"
          git config user.email 
          git config user.name
          git rm euronews.m3u
          git commit -am "euronwews.m3u deleted"
          chmod +x exec_grabberOD.sh && ./exec_grabberOD.sh
          git add -f euronews.m3u
          git status
          git commit -m "euronews.m3u playlist updated."
          git push
